// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SRD_UltraBase","status":true,"description":"Contains code required for HUD Maker Ultra. Does not affect the RPG Maker codebase.","parameters":{}},
{"name":"SRD_HUDMakerUltra","status":true,"description":"Allows you to create and use HUDs for the map and battles.\r\nRequires the HUD Maker Ultra editor.","parameters":{"Auto-Reload HUD Data":"false","Enable Screenshots":"false","Hide Battle Status Window":"false","Hide Battle Selection Window":"false","Fade During Events":"true","Event Fade Opacity":"125","Fade Duration":"10","Map Visibility Code":"return true;","Battle Visibility Code":"return true;"}},
{"name":"WD_Quest","status":true,"description":"Custom Quest Plugin for RPG Maker MZ","parameters":{"linebreak1":"================","Title":"Objectifs","fontsize":"40","dynamicDescSize":"true","paddingValue":"50","descriptionSize":"20","infoalign":"center","listSize":"20","listAlign":"center","linebreak2":"================","giverprefix":"","areaprefix":"","statusname":"Statut :","questcompleted":"Complétée !","questongoing":"En cours","questfailed":"Ratée","linebreak3":"================","menucommand":"true","commandname":"Objectifs","linebreak4":"================","titleFlag":"true","layoutAlign":"layout1","layoutSize":"size2","touchCancel":"true","skinSettings":"{\"skinFlag\":\"true\",\"skinName\":\"Window-1\",\"redT\":\"0\",\"greenT\":\"0\",\"blueT\":\"0\"}"}},
{"name":"GALV_MessageStylesMZ","status":true,"description":"(v.2.1) 'Show Text' windows float above characters and change visuals during game.","parameters":{"iIndicator":"2,0,-12","mPadding":"0,0,0,0","invertPos":"true","aGraphic":"WindowArrow","yOffset":"120"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"MAUI_RemoveOutlnes","status":true,"description":"This plugin removes outlines for RPG Maker MV and RPG Maker MZ.\r\nContact me via email: josephdevelops","parameters":{}}
];
